-- INS.SEX_UPON_INTAKE = Intact ANS OUTS.SEX_UPON_INTAKE != INTACT
SELECT 
O.ANIMAL_ID AS ANIMAL_ID, 
O.ANIMAL_TYPE AS ANIMAL_TYPE,
O.NAME AS NAME
FROM ANIMAL_OUTS AS O
    JOIN ANIMAL_INS AS I
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' AND O.SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY O.ANIMAL_ID ASC;
