-- O.DATETIME IS NULL, I.DATETIME ORDER BY DESC LIMIT 3
SELECT I.NAME AS NAME, I.DATETIME AS DATETIME
FROM ANIMAL_INS AS I
    LEFT JOIN ANIMAL_OUTS AS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME ASC
LIMIT 3;