SELECT R.ITEM_ID, R.ITEM_NAME, R.RARITY
FROM ITEM_INFO II
JOIN ITEM_TREE IT
    ON II.ITEM_ID = IT.PARENT_ITEM_ID
JOIN ITEM_INFO R
    ON IT.ITEM_ID = R.ITEM_ID
WHERE II.RARITY = 'RARE'
ORDER BY R.ITEM_ID DESC;